---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: moathsalman
spec:
  encryptedData:
    token: AgBVZK6bshsz2acuSTK4b2xNNPIwyuryD/CMbYvXsmwFBzYeaNyvhjgMy1kdWLMRFsn59qZNt0bdjL7GwDEPahN6RjaNy1YkiRyK55aSHygupx/qZD1V2fhgyAJNLAaryIs6OouclB1hFWCfqkSrH0sh2nLTSlC3yL7F5mk2LsvcbE2LPfri0iwpMXfUb+410PBi0stuWLKIdciDY0Kfy0DI2S7bGBUSdcszJ+Vnj3EAFJfpwL8fXvD4XY+2e9amspJEMnLK9wv8HJtgSlhL3x6RNrZaeZkTgGzYnb/jhh/uJGJ656ePjO0hEFYl+Lrlflu0Pg7IZqWOAx7gpL2BZkj19oIXfVFTJp2zoluEDMleO2/HNaTd0bzAXaEmhMEZnmsfKDsDpljK59AZcHH1pZP9LoNS4XxQeomA58q/toEwLU3RGqkMLGQPlWo+eQlTTKqFTcCulhPO3rKrMhY11bno8EMXu5KzP946zdvThEBNG/97Gm+oaHpTSJd2Opu8beX4cNE4Q9OHb39cojSrC6kaG4trP0J5DL8ip+eNm6jufqBH5RDJPH9A96UZkcHtDy0+T1MNk6WLtRzPRudedA2+VZWP+Ii8CjM0Rt0lNC7ZGYjG6DU9uzHxccg5sWOi4QX+C+TOku2XIpM3Co+vveBLcpRTxPFFWSCA1Udga1PFSzmTyddoNyY4m0fRjsyBuCwQws3m3/+O8qAxrQCyde2uOqil1+8L2eZMtUSUmR1MFPG1N2xiYuDmTUnP6ROnSGRhh6WaSii3IOj8yfd9zpVYvoZ+bW3q9yL2esczJHb01EjQWPw/nuVmNji1hb+iCL3N7ylaM/Rk9j5uansRdpFQ2YnEd1prG2taDA4Kn5u4D21XYsgIqglCbli5Ap4D5ZjhCMUbIia/24+ruSJnUSjE16mo1CYycndWHJRnDhzIktGXSiY69nq0
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: moathsalman
