apiVersion: v1
kind: ConfigMap
metadata:
  name: moathsalman-site
  namespace: moathsalman
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Moath Salman</title></head>
    <body>
      <h1>Hello from lemoncluster</h1>
    </body>
    </html>