apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: elastic
  namespace: logging
spec:
  interval: 24h # Check for updates every 24 hours
  url: https://helm.elastic.co # URL of the Elastic Helm repository